n = input("Enter a number (1000-9999): ")
a = int(n[0])
b = int(n[1])
c = int(n[2])
d = int(n[3])
print("You entered number "+n+".")
print("Number",n,"is separater to be "+str(a)+", "+str(b)+", "+str(c)+" and "+str(d)+".")
if (a>b and a>c and a>d) : print("The maximum number is "+str(a)+".")
elif (b>a and b>c and b>d) : print("The maximum number is "+str(b)+".")
elif (c>a and c>b and c>d) : print("The maximum number is "+str(c)+".")
else : print("The maximum number is "+str(d)+".")