s = input("Enter a string: ")
print("You enterd a string",'"'+s+'".')
print("Capital only first character of word ==>",s.title())
print("All uppercase ==>",s.upper())
print("All Lowercase ==>",s.lower())
print('Replace a space with "---" ==>',s.replace(" ","---"))